# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site # 整站的基本信息
title: Wander's Blog #网站标题
subtitle: 温故而知新 #网站副标题
description: 说事实 讲道理 有图有真相 #网站描述，给搜索引擎看的，在生成html中的head->meta中可看到
author: Wander.Zeng #网站作者
language: zh-Hans #网站使用的语言
timezone: Asia/Shanghai #网站时区。Hexo 预设使用您电脑的时区

# URL #绑定域名(个人域名)后，欲创建sitemap.xml需要配置该项
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://0613.me #你的域名
root: / ##网站根目录，可以自定义如/blog/
permalink: :year/:month/:day/:title/ #文章的永久链接
permalink_defaults: #永久链接中各部分的默认值

# Directory
source_dir: source #资源文件夹，这个文件夹用来存放内容。默认值是source
public_dir: public #公共文件夹，这个文件夹用于存放生成的站点文件。默认值是public
tag_dir: tags #标签文件夹。默认值是tags
archive_dir: archives #归档文件夹。默认值是archives
category_dir: categories #分类文件夹。默认值是categories
code_dir: downloads/code #默认值是downloads/code
i18n_dir: :lang #国际化文件夹。默认值:lang
skip_render: # 跳过指定文件的渲染

# Writing #文章布局、写作格式的定义，不修改
new_post_name: :title.md # 新文章的文件名称
default_layout: post #预设布局
titlecase: false # Transform title into titlecase
external_link: true # 在新标签中打开链接
filename_case: 0 #把文件名称转换为小写或大写
render_drafts: false #显示草稿
post_asset_folder: false #启动 Asset 文件夹
relative_link: false
future: true
highlight: #代码高亮
  enable: true
  line_number: true #是否显示行号
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized #默认分类
category_map: #分类别名
tag_map: #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD #文章发表时间的显示格式
time_format: HH:mm:ss

# Pagination #每页显示文章数，可以自定义
## Set per_page to 0 to disable pagination
per_page: 10 #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page #分页目录

# Extensions #这里配置站点所用主题和插件
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next #当前主题名称

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
      github: git@personal.github.wanderhero:wanderhero/wanderhero.github.io.git,master
      coding: git@personal.coding.wander:wander/wander.git,master
      oschina: git@personal.oschina.wanderhero:wanderhero/wanderhero.git,master
  #branch: master

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 新增搜索
algolia: 
  applicationID: L34XZDY661 
  apiKey: e2f02dacf5ff8155a9f9390f100de654 
  adminApiKey: 9d90fc74894c4dde5b1447d278466a13 
  indexName: 42bf5dc7558a177308743da34255dbd4 
  chunkSize: 5000 

# 设置 RSS
feed: 
  type: feed
  path: feed.xml
  limit: 20
  hub: 
  content: 'true'

# 修改启动端口
server: 
  port: 5000
  log: false
  ip: 0.0.0.0
  compress: false
  header: true
